[PHP]
; Upload
upload_max_filesize = 110M
post_max_size       = 120M
max_file_uploads    = 20

; Memory & waktu eksekusi
memory_limit        = 256M
max_execution_time  = 300
max_input_time      = 300

; Error
display_errors      = Off
log_errors          = On
error_log           = /var/log/php_errors.log

; Timezone
date.timezone       = Asia/Jakarta

; Session (file — cocok untuk single server)
session.driver      = file
session.lifetime    = 120

; Opcache (percepat PHP)
opcache.enable           = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files   = 4000
opcache.revalidate_freq         = 2
opcache.fast_shutdown           = 1
